name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1nXaaBVQ8T1mPGv6xqjDQxmdHcW_3b71aGZQjhsGb8ytRZjFT
        USER_PASS: 33767078
     - name: Don't kill instace
       if: ${{ failure() }}
       run: slee  12h
